version: "3.7"
services:
 db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

 adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 redis:
  image: redis
  container_name: cache
  expose:
    - 6379



 sidekiq:
   depends_on:
      - "db"
      - "redis"
   links:
      - "db"
      - "redis"
   build: .
   command: bundle exec sidekiq
   volumes:
      - ".:/app"
   environment:
     REDIS_URL: redis://redis:6379/0
     
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: instabugElasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"
 kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: instabugKibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "SERVER_NAME=127.0.0.1"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
 web:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - '.:/project'
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/0
    expose:
      - 3000

volumes:
  redis:
  db:
  web:
  certs:
    driver: local
  esdata01:
    driver: local
  kibanadata:
    driver: local